project_id = "mindquest"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[local_smtp]
port = 54324

[storage]

[storage.buckets.book-covers]
public = true

[storage.buckets.user-avatars]
public = true

[storage.buckets.lesson-media]
public = false

[storage.buckets.lottie-animations]
public = true
