import 'dart:async';
import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:uuid/uuid.dart';

import '../../../../core/config/app_config.dart';
import '../models/chat_message.dart';

/// Data source for the AI Coach chat feature.
///
/// Conversations and messages are stored in Supabase.
/// AI responses are generated by the `ai-tutor` Edge Function with streaming.
class AiCoachDataSource {
  const AiCoachDataSource(this._supabase);

  final SupabaseClient _supabase;

  // ---------------------------------------------------------------------------
  // Conversations
  // ---------------------------------------------------------------------------

  Future<List<Map<String, dynamic>>> fetchConversations(
      String userId) async {
    return _supabase
        .from('conversations')
        .select('id, title, lesson_id, book_id, created_at, updated_at')
        .eq('user_id', userId)
        .order('updated_at', ascending: false)
        .limit(50);
  }

  Future<String> createConversation(
      String userId, String? lessonId, String? bookId) async {
    final id = const Uuid().v4();
    await _supabase.from('conversations').insert({
      'id': id,
      'user_id': userId,
      'lesson_id': lessonId,
      'book_id': bookId,
      'title': 'New Conversation',
      'created_at': DateTime.now().toIso8601String(),
      'updated_at': DateTime.now().toIso8601String(),
    });
    return id;
  }

  // ---------------------------------------------------------------------------
  // Messages
  // ---------------------------------------------------------------------------

  Future<List<ChatMessage>> fetchMessages(String conversationId) async {
    final rows = await _supabase
        .from('messages')
        .select('id, role, content, created_at')
        .eq('conversation_id', conversationId)
        .order('created_at');

    return rows.map<ChatMessage>((row) => ChatMessage(
          id: row['id'] as String,
          role: row['role'] as String,
          content: row['content'] as String,
          createdAt: DateTime.tryParse(row['created_at'] as String? ?? '') ??
              DateTime.now(),
        )).toList();
  }

  // ---------------------------------------------------------------------------
  // Send message with streaming
  // ---------------------------------------------------------------------------

  /// Sends [message] to the `ai-tutor` Edge Function and returns a [Stream]
  /// of token strings as they arrive from the server-sent events endpoint.
  Stream<String> sendMessageStreaming({
    required String conversationId,
    required String message,
    String? lessonContext,
    String? bookContext,
  }) async* {
    // Persist the user message first.
    await _supabase.from('messages').insert({
      'id': const Uuid().v4(),
      'conversation_id': conversationId,
      'role': 'user',
      'content': message,
      'created_at': DateTime.now().toIso8601String(),
    });

    // Call the Edge Function with streaming.
    final session = _supabase.auth.currentSession;
    final token = session?.accessToken ?? '';

    // Invoke via the Supabase functions client (non-streaming).
    // For true streaming, the Edge Function URL is derived from the
    // Supabase project ref stored in the client's URL.
    final uri = Uri.parse('${AppConfig.supabaseUrl}/functions/v1/ai-tutor');

    final request = http.Request('POST', uri)
      ..headers['Authorization'] = 'Bearer $token'
      ..headers['Content-Type'] = 'application/json'
      ..body = jsonEncode({
        'conversation_id': conversationId,
        'message': message,
        'lesson_context': lessonContext,
        'book_context': bookContext,
      });

    final response =
        await http.Client().send(request).timeout(const Duration(seconds: 60));

    if (response.statusCode != 200) {
      throw Exception(
          'AI tutor error: HTTP ${response.statusCode}');
    }

    String assistantContent = '';
    final assistantMsgId = const Uuid().v4();

    await for (final chunk
        in response.stream.transform(utf8.decoder)) {
      // SSE lines start with "data: "
      for (final line in chunk.split('\n')) {
        if (line.startsWith('data: ')) {
          final data = line.substring(6).trim();
          if (data == '[DONE]') break;
          try {
            final parsed = jsonDecode(data) as Map<String, dynamic>;
            final delta =
                parsed['choices']?[0]?['delta']?['content'] as String?;
            if (delta != null && delta.isNotEmpty) {
              assistantContent += delta;
              yield delta;
            }
          } catch (_) {
            // Skip malformed SSE chunks.
          }
        }
      }
    }

    // Persist the full assistant response.
    if (assistantContent.isNotEmpty) {
      await _supabase.from('messages').insert({
        'id': assistantMsgId,
        'conversation_id': conversationId,
        'role': 'assistant',
        'content': assistantContent,
        'created_at': DateTime.now().toIso8601String(),
      });
    }
  }
}
