-- =============================================================================
-- 26_recommendations.sql
-- ML / rule-based content recommendations for each user
-- =============================================================================

CREATE TABLE IF NOT EXISTS IF NOT EXISTS recommendations (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    item_type       TEXT        NOT NULL CHECK (item_type IN ('book', 'lesson')),
    item_id         UUID        NOT NULL,
    score           FLOAT       NOT NULL DEFAULT 0,
    reason          TEXT,
    is_dismissed    BOOLEAN     NOT NULL DEFAULT false,
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ,

    -- One active recommendation per (user, item_type, item_id) pair
    CONSTRAINT recommendations_user_item_unique UNIQUE (user_id, item_type, item_id),

    CONSTRAINT recommendations_score_non_negative CHECK (score >= 0),
    CONSTRAINT recommendations_expires_after_generated
        CHECK (expires_at IS NULL OR expires_at > generated_at)
);

-- Primary feed query: undismissed, non-expired recs for a user, highest score first
CREATE INDEX IF NOT EXISTS IF NOT EXISTS idx_recommendations_user_active
    ON recommendations (user_id, score DESC, is_dismissed, expires_at)
    WHERE is_dismissed = false;

-- Filter by content type
CREATE INDEX IF NOT EXISTS IF NOT EXISTS idx_recommendations_user_type
    ON recommendations (user_id, item_type, is_dismissed, expires_at);

-- Support expiry sweeps (background job to purge/regenerate stale recs)
CREATE INDEX IF NOT EXISTS IF NOT EXISTS idx_recommendations_expires_at
    ON recommendations (expires_at)
    WHERE expires_at IS NOT NULL AND is_dismissed = false;

COMMENT ON TABLE  recommendations               IS 'Personalised content recommendations generated by the recommendation engine or rules.';
COMMENT ON COLUMN recommendations.item_type     IS 'Discriminator: book | lesson.';
COMMENT ON COLUMN recommendations.item_id       IS 'UUID of the recommended row in the corresponding table.';
COMMENT ON COLUMN recommendations.score         IS 'Recommendation confidence/relevance score (higher is better).';
COMMENT ON COLUMN recommendations.reason        IS 'Human-readable explanation shown to the user, e.g. "Based on your interest in investing".';
COMMENT ON COLUMN recommendations.is_dismissed  IS 'Set to true when the user explicitly dismisses the recommendation.';
COMMENT ON COLUMN recommendations.generated_at  IS 'When this recommendation was computed.';
COMMENT ON COLUMN recommendations.expires_at    IS 'After this timestamp the recommendation should no longer be surfaced; NULL = never expires.';
